#!/bin/sh

# This code is from radvd package found on:
# http://openwrt.org/ipkg/

if [ ! -f /etc/radvd.conf ] ; then
	echo
	echo
	echo See /etc/radvd.conf for configuration.
	echo
	cp /etc/radvd.conf.example /etc/radvd.conf
fi
