#
# Copyright (C) 2018 Florian Eckert <fe@dev.tdt.de>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for hnet
LUCI_DEPENDS:=

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Steven Barth <steven@midlink.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
