#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/ar71xx.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(ar71xx_board_name)

case "$board" in
all0258n | \
cap4200ag | \
mr600)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x10000" "0x10000"
	;;
alfa-ap96 | \
all0315n | \
om2p | \
om2p-hs | \
om2p-lc)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x40000" "0x40000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
