#!/bin/sh
#
# Copyright (C) 2013-2014 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/imx6.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(imx6_board_name)

case "$board" in
"wandboard")
	ubootenv_add_uci_config "/dev/mmcblk0" "0x60000" "0x2000" "0x2000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
