#!/bin/sh
#
# Copyright (C) 2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/kirkwood.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh

hardware=$(kirkwood_hardware_name)

case "$hardware" in
"RaidSonic ICY BOX IB-NAS6210")
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x20000" "0x20000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
