#!/bin/sh
#
# Copyright (C) 2012-2013 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

case "`cat /proc/device-tree/model`" in
"Cloud Engines Pogoplug E02" | \
"RaidSonic ICY BOX IB-NAS62x0 (Rev B)")
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x20000" "0x20000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
