#!/bin/sh /etc/rc.common

START=80
STOP=85
USE_PROCD=1

create_symlink_if_missing() {
    src="$1"
    dst="/usr/lib/${src##*/}"

    if [ ! -e "$dst" ] && [ ! -L "$dst" ]; then
        if [ -e "$src" ]; then
            ln -s "$src" "$dst"
            echo "Created symlink: $dst -> $src"
        else
            echo "Source file not found: $src"
        fi
    else
        echo "File already exists: $dst"
    fi
}

start_service() {

    if [ ! -d /var/log/accel-ppp ]; then
        mkdir -p /var/log/accel-ppp
        echo "Created directory /var/log/accel-ppp."
    else
        echo "Directory /var/log/accel-ppp already exists."
    fi

    for src in \
        /usr/lib/accel-ppp/libconnlimit.so \
        /usr/lib/accel-ppp/libvlan-mon.so \
        /usr/lib/accel-ppp/libradius.so \
        /usr/lib/accel-ppp/libsigchld.so \
        /usr/lib/accel-ppp/libippool.so
    do
        create_symlink_if_missing "$src"
    done

    procd_open_instance
    procd_set_param command /usr/sbin/accel-pppd -c /etc/accel-ppp/accel-ppp.conf
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}