# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SSR Libev Server
LUCI_DEPENDS:=+libsodium +shadowsocksr-libev-server
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=6-20190704

include ../luci

# call BuildPackage - OpenWrt buildroot signature


