#!/bin/sh

# Make sure password and group databases exist
if [ ! -f /etc/passwd ]; then
   echo -e "root::0:0::/tmp:/bin/sh\nnobody:x:65534:65534:nobody:/tmp:/bin/sh\nsshd:x:100:65534:sshd:/var:/bin/false\n" > /etc/passwd
   [ -f /etc/group ] || echo -e "root:x:0:\nnogroup:x:65534:\n" > /etc/group
   echo "\n\nNOTICE: SSH requires proper root password to be configured, set it now."
   passwd
fi
                
