#!/bin/sh
. /etc/nvram.sh

[ "$(uname -r|grep -c 2.4)" = "1" ] && {
        echo "S" > /proc/jffs2_bbc
}

vconfig set_name_type VLAN_PLUS_VID_NO_PAD

HOSTNAME=$(nvram get wan_hostname)
HOSTNAME=${HOSTNAME%%.*}
echo ${HOSTNAME:=OpenWrt}>/proc/sys/kernel/hostname

mkdir -p /var/run
mkdir -p /var/log
touch /var/log/wtmp
touch /var/log/lastlog
[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

for iface in $(/sbin/ifconfig -a | awk '{print $1}' | grep eth); do
	/usr/bin/env -i ACTION=add INTERFACE="$iface" /sbin/hotplug net
done

sed 's/^[^#]/insmod &/' /etc/modules /etc/modules.d/* 2>&-|ash

ifconfig lo 127.0.0.1 up
ifconfig eth0 promisc

