#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2018 Rosy Song <rosysong@rosinson.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Rosy File Server
LUCI_DEPENDS:=+luci-compat +luci-base +rosy-file-server

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
