#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/sbin/ucentral-wifi

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_close_instance
}
