src-git packages https://git.openwrt.org/feed/packages.git
src-git luci https://git.openwrt.org/project/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git modemfeed https://github.com/koshev-msk/modemfeed.git
src-git darkmoon https://github.com/kamikaonashi/openwrt-package-darkmoon.git
src-git poweroff https://github.com/sirpdboy/luci-app-poweroffdevice.git
src-link fantastic_packages /home/farmer/openwrt/fantastic_packages_src
