reponame: github.com/untangle/openwrt
description: |
  MFW fork of openwrt/openwrt, with minimal patches
users:
  maintainers:
    - abriles@arista.com
    - aornstein@arista.com
    - al.parker@arista.com
    - amit.mishra@arista.com
    - acooke@arista.com
    - avinash.dige@arista.com
    - crasmussen@arista.com
    - cblaise@arista.com
    - cvarga@arista.com
    - dhadarau@arista.com
    - iramasamy@arista.com
    - jphillips@arista.com
    - jsommerville@arista.com
    - ksridhar@arista.com
    - lnicoara@arista.com
    - manuwela.kanade@arista.com
    - sdelafond@arista.com
    - smitropoulos@arista.com
    - sumedha.game@arista.com
    - utkarsh.pratapsingh@arista.com
    - vishal.mane-ext@arista.com
    - yogesh.chhetri@arista.com
  watchers:
    - bruce@arista.com
    - cmercer@arista.com
    - drush@arista.com
    - jcoffin@arista.com
    - manoj@arista.com
    - prashant.karunakaran@arista.com
    - sheck@arista.com
    - tkovalev@arista.com
x-bar:
  version: production
epoch: 1
