#!/bin/sh
# 配置 PPPoE 接口 BLUE4WAN + 防火墙 + 常用 NAT/DNS/MSS 设置

# 添加 PPPoE 接口
uci -q delete network.BLUE4WAN
uci set network.BLUE4WAN="interface"
uci set network.BLUE4WAN.proto="pppoe"
uci set network.BLUE4WAN.device="lan4"
uci set network.BLUE4WAN.username="your_pppoe_username"
uci set network.BLUE4WAN.password="your_pppoe_password"
uci set network.BLUE4WAN.ipv6="auto"

# 添加 IPv6 接口
uci -q delete network.BLUE4WAN6
uci set network.BLUE4WAN6="interface"
uci set network.BLUE4WAN6.proto="dhcpv6"
uci set network.BLUE4WAN6.device="lan4"

# 防火墙 zone
uci -q delete firewall.BLUE4WAN
uci set firewall.BLUE4WAN="zone"
uci set firewall.BLUE4WAN.name="BLUE4WAN"
uci add_list firewall.BLUE4WAN.network="BLUE4WAN"
uci add_list firewall.BLUE4WAN.network="BLUE4WAN6"
uci set firewall.BLUE4WAN.input="REJECT"
uci set firewall.BLUE4WAN.output="ACCEPT"
uci set firewall.BLUE4WAN.forward="REJECT"
uci set firewall.BLUE4WAN.masq="1"
uci set firewall.BLUE4WAN.mtu_fix="1"

# 转发规则 LAN -> BLUE4WAN
uci -q delete firewall.lan2bluewan
uci set firewall.lan2bluewan="forwarding"
uci set firewall.lan2bluewan.src="lan"
uci set firewall.lan2bluewan.dest="BLUE4WAN"

# 允许 LAN 出口 DNS
uci -q delete firewall.allow_dns
uci set firewall.allow_dns="rule"
uci set firewall.allow_dns.name="Allow-DNS"
uci set firewall.allow_dns.src="lan"
uci set firewall.allow_dns.dest_port="53"
uci set firewall.allow_dns.proto="tcp udp"
uci set firewall.allow_dns.target="ACCEPT"

# 允许 LAN 出口 DHCP
uci -q delete firewall.allow_dhcp
uci set firewall.allow_dhcp="rule"
uci set firewall.allow_dhcp.name="Allow-DHCP"
uci set firewall.allow_dhcp.src="lan"
uci set firewall.allow_dhcp.dest_port="67-68"
uci set firewall.allow_dhcp.proto="udp"
uci set firewall.allow_dhcp.target="ACCEPT"

uci commit network
uci commit firewall

exit 0
