#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

local rfkill_state=0

wifi_rfkill_set() {
	uci set wireless.$1.disabled=$rfkill_state
}

wifi_rfkill_check() {
	local disabled
	config_get disabled $1 disabled
	[ "$disabled" = "1" ] || rfkill_state=1
}

config_load wireless
config_foreach wifi_rfkill_check wifi-device
config_foreach wifi_rfkill_set wifi-device
uci commit wireless
wifi up
