#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=60
USE_PROCD=1

log() {
	logger -t "iframe" "$@"
}

start_service()
{
	if [ ! -d /tmp/www ]; then
		mkdir -p /tmp/www
	fi
	/usr/lib/iframe/create.sh &
	/usr/lib/iframe/status.sh &
}
