include $(TOPDIR)/rules.mk

LUCI_TITLE:= Net-SNMP LuCI interface
LUCI_DEPENDS:=+luci-compat +luci-base
LUCI_PKGARCH:=all
LUCI_DESCRIPTION:=Some common net-snmp config items. In no way is this comprehensive.

PKG_MAINTAINER:= Karl Palsson <karlp@etactica.com>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
