#ifndef _XPON_GLOBAL_XMCS_CONST_H_
#define _XPON_GLOBAL_XMCS_CONST_H_

#include "../public/xmcs_const.h"

#define XPON_QUEUE_NUMBER			8

#ifdef TCSUPPORT_CPU_EN7521
    #define XPON_CHANNEL_NUMBER		(32)
    #define GPON_OMCI_INTERFACE	    (0x1FF)
    #define GPON_MAX_ANI_INTERFACE	(256)
#else
    #define XPON_CHANNEL_NUMBER		(16)
    #define GPON_OMCI_INTERFACE	    (0x3F)
    #define GPON_MAX_ANI_INTERFACE	(32)
#endif

#define XPON_SHAPING_NUMBER			(32)

typedef enum {
	GPON_EQD_OFFSET_FLAG_ADD = 0,
	GPON_EQD_OFFSET_FLAG_SUBTRACT,
} GPON_EQD_OFFSET_FLAG_t ;

typedef enum {
	GPON_INT_PLOAMD_RECV = 0,	/* 0 */
	GPON_INT_PLOAMU_SEND,
	GPON_INT_SN_REQ_RECV,
	GPON_INT_SN_ONU_SEND_O3,
	GPON_INT_RANGING_REQ_RECV,
	GPON_INT_ONU_SEND_O4,		/* 5 */
	GPON_INT_SN_REQ_CRS,
	GPON_INT_LOS_GEN_DEL,
	GPON_INT_AES_KEY_SWITCH_DONE,
	GPON_INT_TOD_UPDATE_DONE,
	GPON_INT_TOD_1PPS,			/* 10 */
	GPON_INT_DYING_GASP_SEND,
	GPON_INT_RX_ERR = 16,		/* 16 */
	GPON_INT_FIFO_ERR,
	GPON_INT_BST_SGL_DIFF,
	GPON_INT_TX_LATE_START,
	GPON_INT_RX_EOF_ERR,
	GPON_INT_RX_GEM_INTLV_ERR,	/* 21 */
#ifdef TCSUPPORT_CPU_EN7521
	GPON_INT_BFIFO_FULL,		/* 22 */
	GPON_INT_SFIFO_FULL,		/* 23 */
#endif
	GPON_INT_O5_EQD_ADJ_DONE,	/* 24 */
#ifdef TCSUPPORT_CPU_EN7521
	GPON_INT_OLT_DS_FEC_CHG,	/* 25 */
	GPON_INT_ONU_US_FEC_CHG,	/* 26 */
	GPON_INT_POP_UP_RECV_IN_O6,
	GPON_INT_FWI,
	GPON_INT_LWI,
	GPON_INT_BWM_STOP_TIME_ERR,	/* 30 */
#endif
} GPON_INTERRUPT_MASK_T ;


typedef enum {
	MSG_ERR		= 0x0001,
	MSG_WARN	= 0x0002,
	MSG_INT		= 0x0004,
	MSG_ACT		= 0x0008,
	MSG_OAM		= 0x0010,
	MSG_OMCI	= 0x0020,
	MSG_TRACE	= 0x0040,
	MSG_CONTENT	= 0x0080,
	MSG_DBG		= 0x0100,
	MSG_EQD		= 0x0200,
	MSG_XMCS	= 0x0400
} xPON_DebugMsg_t ;


#endif /*_XPON_GLOBAL_XMCS_CONST_H_ */

