#!/bin/sh /etc/rc.common
#
# Copyright (C) 2011 OpenWrt.org
#

START=11

SERVICE_DAEMONIZE=1

boot() {
	if [ -r /lib/ar71xx.sh ]; then
		. /lib/ar71xx.sh
		local board=$(ar71xx_board_name)

		case "$board" in
			"om2p"|"om2p-hs")
				service_start /sbin/om-watchdog 12
				;;
			"om2pv2"|"om2p-lc")
				service_start /sbin/om-watchdog 26
				;;
			"mr600v2")
				service_start /sbin/om-watchdog 15
				;;
		esac
	else
		#we assume it is om1p in this case
		service_start /sbin/om-watchdog 3
	fi
}
