#!/bin/sh
is_dirty() {
	grep Broadcom /proc/cpuinfo >&- || return 1
	OFFSET="$(($(hexdump -v /dev/mtdblock/1 -s 20 -n 2 -e '"%d"')-1))"
	return $(hexdump -v /dev/mtdblock/1 -s $OFFSET -n 1 -e '"%d"')
}

size=$(awk '/Mem:/ {l=5242880;print((s=$2/2)<l)?$2-l:s}' /proc/meminfo)
mount none /tmp -t tmpfs -o size=$size

if [ "$1" != "failsafe" ]; then 
	mtd unlock linux
	mount | grep jffs2 >&-
	if [ $? = 0 ] ; then
		if [ $(cat /proc/mtd | wc -l) = 6 ]; then
			mtd erase OpenWrt
			jffs2root --move
		else
			mount -o remount,rw /dev/root /
		fi
	else
		. /bin/firstboot
		is_dirty 
		[ $? != 0 ] && {
			echo "switching to jffs2"
			mount /dev/mtdblock/4 /jffs -t jffs2
			pivot /jffs /rom
		} || {
			echo "jffs2 unusable; using ramdisk"
			ramoverlay
		}
	fi
fi

mount none /tmp -t tmpfs -o remount,nosuid,nodev,mode=1777
mkdir -p /dev/pts
mount none /dev/pts -t devpts
mount -t sysfs none /sys 2>&-
