# From https://github.com/DarkDean89/luci-app-filebrowser
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for File Browser Mini
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=5-20190423

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature