#!/bin/sh /etc/rc.common

USE_PROCD=1

# starts before dnsmasq starts
START=95
# stops before networking stops
STOP=10

PROG=/usr/bin/dnscrypt-proxy
CONFIGFILE=/etc/dnscrypt-proxy/dnscrypt-proxy.toml

start_service() {
        procd_open_instance
        procd_set_param command "$PROG" -config "$CONFIGFILE"
        procd_set_param file "$CONFIGFILE"
        procd_set_param respawn
        procd_close_instance
}
