/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_OMCI_H
#define _UAPI_LINUX_OMCI_H

#define OMCI_GENL_NAME		"omci"
#define OMCI_GENL_VERSION	11
#define OMCI_MAX_PDU_LEN	1980
#define OMCI_MAX_ATTR_DATA	32
#define OMCI_MAX_CONFIG_VALUE	64
#define OMCI_VLAN_FILTER_MAX_ENTRIES	12
#define OMCI_EXT_VLAN_MAX_RULES	32
#define OMCI_EXT_VLAN_RULE_LEN	16
#define OMCI_OLT_VENDOR_ID_LEN	4
#define OMCI_OLT_EQUIPMENT_ID_LEN	20
#define OMCI_OLT_VERSION_LEN	14

/**
 * enum omci_cmd - Generic Netlink commands
 *
 * Raw transport commands are retained for diagnostics. The in-kernel agent
 * owns normal OMCI request processing and userspace is not in the response
 * path.
 */
enum omci_cmd {
	OMCI_CMD_UNSPEC,
	OMCI_CMD_GET,
	OMCI_CMD_BIND,
	OMCI_CMD_UNBIND,
	OMCI_CMD_TX,
	OMCI_CMD_RX,
	OMCI_CMD_EVENT,
	OMCI_CMD_AGENT_SET,
	OMCI_CMD_CONFIG_GET,
	OMCI_CMD_CONFIG_SET,
	OMCI_CMD_MIB_GET,
	OMCI_CMD_MIB_SET,
	OMCI_CMD_MIB_DELETE,
	OMCI_CMD_MIB_RESET,
	OMCI_CMD_MIB_NEXT,
	OMCI_CMD_CLASS_GET,
	OMCI_CMD_CLASS_NEXT,

	__OMCI_CMD_MAX,
};

#define OMCI_CMD_MAX (__OMCI_CMD_MAX - 1)

/**
 * enum omci_attr - Generic Netlink attributes
 */
enum omci_attr {
	OMCI_ATTR_UNSPEC,
	OMCI_ATTR_DEV_ID,
	OMCI_ATTR_IFINDEX,
	OMCI_ATTR_ONU_ID,
	OMCI_ATTR_GEM_PORT_ID,
	OMCI_ATTR_STATE,
	OMCI_ATTR_FLAGS,
	OMCI_ATTR_CAPABILITIES,
	OMCI_ATTR_SEQUENCE,
	OMCI_ATTR_PDU,
	OMCI_ATTR_EVENT,
	OMCI_ATTR_OWNER_PORTID,
	OMCI_ATTR_RX_PACKETS,
	OMCI_ATTR_RX_BYTES,
	OMCI_ATTR_RX_DROPPED,
	OMCI_ATTR_TX_PACKETS,
	OMCI_ATTR_TX_BYTES,
	OMCI_ATTR_TX_ERRORS,
	OMCI_ATTR_AGENT_ENABLED,
	OMCI_ATTR_AGENT_PERMISSIVE,
	OMCI_ATTR_MIB_SYNC,
	OMCI_ATTR_MIB_OBJECTS,
	OMCI_ATTR_AGENT_RESPONSES,
	OMCI_ATTR_AGENT_DUPLICATES,
	OMCI_ATTR_AGENT_UNSUPPORTED,
	OMCI_ATTR_CLASS_ID,
	OMCI_ATTR_ENTITY_ID,
	OMCI_ATTR_ATTR_MASK,
	OMCI_ATTR_ATTR_DATA,
	OMCI_ATTR_ORIGIN,
	OMCI_ATTR_NAME,
	OMCI_ATTR_INDEX,
	OMCI_ATTR_CONFIG_KEY,
	OMCI_ATTR_CONFIG_VALUE,
	OMCI_ATTR_RESULT,
	OMCI_ATTR_PAD,
	OMCI_ATTR_FEC_DOWNSTREAM,
	OMCI_ATTR_FEC_UPSTREAM,
	OMCI_ATTR_TELEMETRY_VALID,
	OMCI_ATTR_BOSA_TEMPERATURE_MC,
	OMCI_ATTR_BOSA_VOLTAGE_UV,
	OMCI_ATTR_BOSA_BIAS_UA,
	OMCI_ATTR_BOSA_TX_POWER_NW,
	OMCI_ATTR_BOSA_RX_POWER_NW,
	OMCI_ATTR_BOSA_ALARMS,
	OMCI_ATTR_VLAN_TAGGING_FILTER,
	OMCI_ATTR_EXTENDED_VLAN,
	OMCI_ATTR_OLT_G,
	OMCI_ATTR_AGENT_FAKE_OMCI,
	OMCI_ATTR_AGENT_FAKE_RESPONSES,
	OMCI_ATTR_CLASS_CATEGORY,
	OMCI_ATTR_CLASS_SUPPORT,
	OMCI_ATTR_CLASS_FLAGS,
	OMCI_ATTR_CONFIG_SOURCE,
	OMCI_ATTR_OLT_PROFILE_CONFIGURED,
	OMCI_ATTR_OLT_PROFILE_EFFECTIVE,
	OMCI_ATTR_OLT_PROFILE_FORCED,
	OMCI_ATTR_OLT_PROFILE_QUIRKS,
	OMCI_ATTR_AGENT_OPERATIONAL,
	OMCI_ATTR_AGENT_DYING_GASP,

	__OMCI_ATTR_MAX,
};

#define OMCI_ATTR_MAX (__OMCI_ATTR_MAX - 1)

/**
 * enum omci_vlan_filter_attr - VLAN tagging filter data attributes
 *
 * OMCI_VLAN_FILTER_ATTR_ENTRIES is a nested array. Each child is a nested
 * attribute set described by enum omci_vlan_filter_entry_attr.
 */
enum omci_vlan_filter_attr {
	OMCI_VLAN_FILTER_ATTR_UNSPEC,
	OMCI_VLAN_FILTER_ATTR_FORWARD_OPERATION,
	OMCI_VLAN_FILTER_ATTR_NUMBER_OF_ENTRIES,
	OMCI_VLAN_FILTER_ATTR_ENTRIES,

	__OMCI_VLAN_FILTER_ATTR_MAX,
};

#define OMCI_VLAN_FILTER_ATTR_MAX (__OMCI_VLAN_FILTER_ATTR_MAX - 1)

enum omci_vlan_filter_entry_attr {
	OMCI_VLAN_FILTER_ENTRY_ATTR_UNSPEC,
	OMCI_VLAN_FILTER_ENTRY_ATTR_INDEX,
	OMCI_VLAN_FILTER_ENTRY_ATTR_TCI,
	OMCI_VLAN_FILTER_ENTRY_ATTR_PBIT,
	OMCI_VLAN_FILTER_ENTRY_ATTR_DEI,
	OMCI_VLAN_FILTER_ENTRY_ATTR_VID,

	__OMCI_VLAN_FILTER_ENTRY_ATTR_MAX,
};

#define OMCI_VLAN_FILTER_ENTRY_ATTR_MAX \
	(__OMCI_VLAN_FILTER_ENTRY_ATTR_MAX - 1)

/**
 * enum omci_extended_vlan_attr - extended VLAN configuration attributes
 *
 * OMCI_EXT_VLAN_ATTR_RULES is a nested array. Each child is a nested
 * attribute set described by enum omci_extended_vlan_rule_attr.
 */
enum omci_extended_vlan_attr {
	OMCI_EXT_VLAN_ATTR_UNSPEC,
	OMCI_EXT_VLAN_ATTR_ASSOCIATION_TYPE,
	OMCI_EXT_VLAN_ATTR_MAX_TABLE_SIZE,
	OMCI_EXT_VLAN_ATTR_INPUT_TPID,
	OMCI_EXT_VLAN_ATTR_OUTPUT_TPID,
	OMCI_EXT_VLAN_ATTR_DOWNSTREAM_MODE,
	OMCI_EXT_VLAN_ATTR_ASSOCIATED_ME,
	OMCI_EXT_VLAN_ATTR_DSCP_TO_PBIT,
	OMCI_EXT_VLAN_ATTR_RULES,

	__OMCI_EXT_VLAN_ATTR_MAX,
};

#define OMCI_EXT_VLAN_ATTR_MAX (__OMCI_EXT_VLAN_ATTR_MAX - 1)

enum omci_extended_vlan_rule_attr {
	OMCI_EXT_VLAN_RULE_ATTR_UNSPEC,
	OMCI_EXT_VLAN_RULE_ATTR_INDEX,
	OMCI_EXT_VLAN_RULE_ATTR_RAW,
	OMCI_EXT_VLAN_RULE_ATTR_DELETE,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_OUTER_PBIT,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_OUTER_VID,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_OUTER_TPID_DEI,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_INNER_PBIT,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_INNER_VID,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_INNER_TPID_DEI,
	OMCI_EXT_VLAN_RULE_ATTR_FILTER_ETHERTYPE,
	OMCI_EXT_VLAN_RULE_ATTR_TAGS_TO_REMOVE,
	OMCI_EXT_VLAN_RULE_ATTR_TREAT_OUTER_PBIT,
	OMCI_EXT_VLAN_RULE_ATTR_TREAT_OUTER_VID,
	OMCI_EXT_VLAN_RULE_ATTR_TREAT_OUTER_TPID_DEI,
	OMCI_EXT_VLAN_RULE_ATTR_TREAT_INNER_PBIT,
	OMCI_EXT_VLAN_RULE_ATTR_TREAT_INNER_VID,
	OMCI_EXT_VLAN_RULE_ATTR_TREAT_INNER_TPID_DEI,

	__OMCI_EXT_VLAN_RULE_ATTR_MAX,
};

#define OMCI_EXT_VLAN_RULE_ATTR_MAX \
	(__OMCI_EXT_VLAN_RULE_ATTR_MAX - 1)

/**
 * enum omci_olt_g_attr - parsed OLT-G identification attributes
 */
enum omci_olt_g_attr {
	OMCI_OLT_G_ATTR_UNSPEC,
	OMCI_OLT_G_ATTR_VENDOR_ID,
	OMCI_OLT_G_ATTR_EQUIPMENT_ID,
	OMCI_OLT_G_ATTR_VERSION,

	__OMCI_OLT_G_ATTR_MAX,
};

#define OMCI_OLT_G_ATTR_MAX (__OMCI_OLT_G_ATTR_MAX - 1)

/**
 * enum omci_class_category - functional managed entity category
 */
enum omci_class_category {
	OMCI_CLASS_CATEGORY_UNSPEC,
	OMCI_CLASS_CATEGORY_EQUIPMENT,
	OMCI_CLASS_CATEGORY_ANI,
	OMCI_CLASS_CATEGORY_UNI,
	OMCI_CLASS_CATEGORY_LAYER2,
	OMCI_CLASS_CATEGORY_LAYER3,
	OMCI_CLASS_CATEGORY_MULTICAST,
	OMCI_CLASS_CATEGORY_VOICE,
	OMCI_CLASS_CATEGORY_SECURITY,
	OMCI_CLASS_CATEGORY_MANAGEMENT,
	OMCI_CLASS_CATEGORY_PERFORMANCE,
	OMCI_CLASS_CATEGORY_XDSL,
	OMCI_CLASS_CATEGORY_LEGACY,
	OMCI_CLASS_CATEGORY_VENDOR,
	OMCI_CLASS_CATEGORY_RESERVED,
	OMCI_CLASS_CATEGORY_OTHER,
};

/**
 * enum omci_class_support - local implementation level
 */
enum omci_class_support {
	OMCI_CLASS_SUPPORT_CATALOG,
	OMCI_CLASS_SUPPORT_SHADOW,
	OMCI_CLASS_SUPPORT_PARSED,
	OMCI_CLASS_SUPPORT_PROVISIONED,
	OMCI_CLASS_SUPPORT_NATIVE,
};

#define OMCI_CLASS_F_STANDARD		(1U << 0)
#define OMCI_CLASS_F_DEPRECATED	(1U << 1)
#define OMCI_CLASS_F_RESERVED		(1U << 2)
#define OMCI_CLASS_F_VENDOR_SPECIFIC	(1U << 3)
#define OMCI_CLASS_F_PERFORMANCE	(1U << 4)
#define OMCI_CLASS_F_TABLE		(1U << 5)
#define OMCI_CLASS_F_DATAPATH		(1U << 6)

enum omci_event {
	OMCI_EVENT_UNSPEC,
	OMCI_EVENT_CHANNEL_UP,
	OMCI_EVENT_CHANNEL_DOWN,
	OMCI_EVENT_STATE_CHANGE,
	OMCI_EVENT_MIB_CHANGE,
	OMCI_EVENT_CONFIG_CHANGE,
	OMCI_EVENT_UNSUPPORTED,
	OMCI_EVENT_PROFILE_CHANGE,
	OMCI_EVENT_OPERATIONAL_CHANGE,
	OMCI_EVENT_DYING_GASP,
};

enum omci_config_key {
	OMCI_CONFIG_UNSPEC,
	OMCI_CONFIG_SERIAL_NUMBER,
	OMCI_CONFIG_VENDOR_ID,
	OMCI_CONFIG_VERSION,
	OMCI_CONFIG_EQUIPMENT_ID,
	OMCI_CONFIG_PASSWORD,
	OMCI_CONFIG_TRAFFIC_MGMT_OPTION,
	OMCI_CONFIG_ONU_TYPE,
	OMCI_CONFIG_UNI_COUNT,
	OMCI_CONFIG_AGENT_ENABLED,
	OMCI_CONFIG_AGENT_PERMISSIVE,
	OMCI_CONFIG_AGENT_FAKE_OMCI,
	OMCI_CONFIG_OLT_PROFILE,
	OMCI_CONFIG_OLT_PROFILE_FORCE,
	OMCI_CONFIG_AGENT_DYING_GASP,

	__OMCI_CONFIG_MAX,
};

#define OMCI_CONFIG_MAX (__OMCI_CONFIG_MAX - 1)

/**
 * enum omci_olt_profile - OLT interoperability policy profile
 * @OMCI_OLT_PROFILE_UNSPEC: no forced profile
 * @OMCI_OLT_PROFILE_GENERIC: standards-oriented profile without vendor quirks
 * @OMCI_OLT_PROFILE_AUTO: detect the effective profile from OLT-G
 * @OMCI_OLT_PROFILE_NOKIA_ALCL: Nokia/Alcatel-Lucent interoperability
 * @OMCI_OLT_PROFILE_DASAN: DASAN interoperability
 * @OMCI_OLT_PROFILE_HUAWEI: Huawei interoperability
 * @OMCI_OLT_PROFILE_FIBERHOME: FiberHome interoperability
 * @OMCI_OLT_PROFILE_ZTE: ZTE interoperability
 */
enum omci_olt_profile {
	OMCI_OLT_PROFILE_UNSPEC,
	OMCI_OLT_PROFILE_GENERIC,
	OMCI_OLT_PROFILE_AUTO,
	OMCI_OLT_PROFILE_NOKIA_ALCL,
	OMCI_OLT_PROFILE_DASAN,
	OMCI_OLT_PROFILE_HUAWEI,
	OMCI_OLT_PROFILE_FIBERHOME,
	OMCI_OLT_PROFILE_ZTE,
};

#define OMCI_OLT_QUIRK_ALLOW_SET_CREATE		(1U << 0)
#define OMCI_OLT_QUIRK_FAKE_UNSUPPORTED_SUCCESS	(1U << 1)
#define OMCI_OLT_QUIRK_IGNORE_UNSUPPORTED_UNI	(1U << 2)
#define OMCI_OLT_QUIRK_FULL_UNI_ENTITY_ID		(1U << 3)
#define OMCI_OLT_QUIRK_SANITIZE_VERSION		(1U << 4)
#define OMCI_OLT_QUIRK_ZTE_VLAN_TAG_MODE		(1U << 5)
#define OMCI_OLT_QUIRK_VENDOR_SPECIFIC_MES		(1U << 6)
#define OMCI_OLT_QUIRK_DASAN_MULTICAST_ANI		(1U << 7)

/**
 * enum omci_config_source - source of a normalized configuration value
 */
enum omci_config_source {
	OMCI_CONFIG_SOURCE_UNSPEC,
	OMCI_CONFIG_SOURCE_DEFAULT,
	OMCI_CONFIG_SOURCE_DEVICE_TREE,
	OMCI_CONFIG_SOURCE_NVMEM,
	OMCI_CONFIG_SOURCE_DRIVER,
	OMCI_CONFIG_SOURCE_NETLINK,
};

enum omci_fec_status {
	OMCI_FEC_STATUS_UNKNOWN,
	OMCI_FEC_STATUS_DOWN,
	OMCI_FEC_STATUS_UP,
};

#define OMCI_TELEMETRY_F_FEC_DOWNSTREAM	(1U << 0)
#define OMCI_TELEMETRY_F_FEC_UPSTREAM		(1U << 1)
#define OMCI_TELEMETRY_F_BOSA_TEMPERATURE	(1U << 2)
#define OMCI_TELEMETRY_F_BOSA_VOLTAGE		(1U << 3)
#define OMCI_TELEMETRY_F_BOSA_BIAS		(1U << 4)
#define OMCI_TELEMETRY_F_BOSA_TX_POWER	(1U << 5)
#define OMCI_TELEMETRY_F_BOSA_RX_POWER	(1U << 6)
#define OMCI_TELEMETRY_F_BOSA_ALARMS		(1U << 7)

enum omci_mib_origin {
	OMCI_MIB_ORIGIN_DEFAULT,
	OMCI_MIB_ORIGIN_LOCAL,
	OMCI_MIB_ORIGIN_OLT,
	OMCI_MIB_ORIGIN_HARDWARE,
};

#define OMCI_F_MIC_PRESENT	(1U << 0)
#define OMCI_F_MIC_VALID	(1U << 1)
#define OMCI_F_CRC_ERROR	(1U << 2)
#define OMCI_F_CHANNEL_UP	(1U << 3)

#define OMCI_CAP_HW_MIC		(1U << 0)
#define OMCI_CAP_BASELINE_AGENT	(1U << 1)
#define OMCI_CAP_TELEMETRY		(1U << 2)

#endif /* _UAPI_LINUX_OMCI_H */
