#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/sshd

log() {
	logger -t "OPENSSH" "$@"
}

start_service() {
	log "Starting SSH"

	for type in rsa ecdsa ed25519; do {
		# check for keys
		key=/etc/ssh/ssh_host_${type}_key
		[ ! -f $key ] && {
			# generate missing keys
			[ -x /usr/bin/ssh-keygen ] && {
				/usr/bin/ssh-keygen -N '' -t $type -f $key 2>&- >&-
			}
		}
	}; done
	mkdir -m 0700 -p /var/empty

	local lport=`grep ^Port /etc/ssh/sshd_config | cut -d " " -f 2`
	[ -z $lport ] && lport=22

	#procd_open_instance
	#procd_add_mdns "ssh" "tcp" "$lport"
	#procd_set_param command $PROG -D
	#procd_close_instance
	
	/usr/sbin/sshd &
}

shutdown() {
	local pid
	local pids
	local pid_mine

	stop

	# kill active clients
	pid_mine="$$"
	pids="$(pidof sshd)"
	for pid in $pids; do
		[ "$pid" = "$pid_mine" ] && continue
		[ -e "/proc/$pid/stat" ] && kill $pid
	done
}
