#!/bin/sh /etc/rc.common

START=20

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd
	sleep 1
}

stop() {
	service_stop /sbin/netifd
}

reload() {
	ubus call network reload
}
