#!/bin/sh /etc/rc.common
START=20
PIDFILE=/var/run/netifd.pid

start() {
	stop
	start-stop-daemon -S -b -m -p $PIDFILE -x /sbin/netifd
}

reload() {
	ubus call network reload
}

stop() {
	[ -e "$PIDFILE" ] || return
	start-stop-daemon -K -p $PIDFILE -x /sbin/netifd
	rm -f "$PIDFILE"
}
