#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=10

system_config() {
	local cfg="$1"
	local hostname
	
	config_get hostname "$cfg" hostname
	echo "${hostname:-OpenWrt}" > /proc/sys/kernel/hostname
}

start() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	vconfig set_name_type DEV_PLUS_VID_NO_PAD
	
	config_load system
	config_foreach system_config system
	
	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	touch /var/log/wtmp
	touch /var/log/lastlog
	ln -s /tmp/resolv.conf.auto /tmp/resolv.conf
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe
	
	# the coldplugging of network interfaces needs to happen later, so we do it manually here
	for iface in $(awk -F: '/:/ {print $1}' /proc/net/dev); do
		/usr/bin/env -i ACTION=add INTERFACE="$iface" /sbin/hotplug-call net
	done
	/sbin/hotplug2 --persistent --max-children 1 &

	# create /dev/root if it doesn't exist
	[ -e /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	load_modules /etc/modules.d/*
}
