#!/bin/sh /etc/rc.common
# (C) 2008 openwrt.org

START=96

load_led() {
	local name
	local sysfs
	local trigger
	local dev
	local mode
	local default
	local delayon
	local delayoff

	config_get sysfs $1 sysfs
	config_get name $1 name "$sysfs"
	config_get trigger $1 trigger "none"
	config_get dev $1 dev
	config_get mode $1 mode "link"
	config_get_bool default $1 default "nil"
	config_get delayon $1 delayon
	config_get delayoff $1 delayoff

	[ -e /sys/class/leds/${sysfs}/brightness ] && {
		echo "setting up led ${name}"
		[ "$default" != nil ] && { 
			[ $default -eq 1 ] && 
				echo 1 >/sys/class/leds/${sysfs}/brightness 
			[ $default -eq 1 ] ||
				echo 0 >/sys/class/leds/${sysfs}/brightness
		}
		echo $trigger > /sys/class/leds/${sysfs}/trigger
		[ "$trigger" == "netdev" -a -n "$dev" ] && {
			echo $dev > /sys/class/leds/${sysfs}/device_name
			echo $mode > /sys/class/leds/${sysfs}/mode
		} 
		[ "$trigger" == "timer" ] && {
			[ -n "$delayon" ] && echo $delayon > /sys/class/leds/${sysfs}/delay_on
			[ -n "$delayoff" ] && echo $delayoff > /sys/class/leds/${sysfs}/delay_off
		}
	}
}

start() {
	[ -e /sys/class/leds/ ] && {
		config_load system
		config_foreach load_led led
	}
}
