#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 2>&1
	done | $LOGGER
}

LOGGER="cat"
[ -x /usr/bin/logger ] && LOGGER="logger -s -p 6 -t sysinit"

. /etc/functions.sh

config_load system
config_get_bool foreground system foreground no

if [ "$1" = "S" -a "$foreground" != "yes" ]; then
	run_scripts "$1" "$2" &
else
	run_scripts "$1" "$2"
fi
