# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - Samba 4 SMB/CIFS fileserver
LUCI_DEPENDS:=+samba4-server

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
