#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /etc/functions.sh
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
[ "x$1" = "x-a" ] && {
	config_cb() {
		[ -z "$2" ] || eval "$0 $2"
	}
	config_load network
	exit
}
include /lib/network
scan_interfaces

cfg=$1
debug "### ifdown $cfg ###"

config_get proto "$cfg" proto
[ -z "$proto" ] && { echo "interface not found."; exit; }

config_get iface "$cfg" device
[ "$proto" = "static" ] && {
	env -i ACTION="ifdown" INTERFACE="$config" DEVICE="$iface" PROTO=static /sbin/hotplug-call "iface" &
}

# call interface stop handler
( type "stop_interface_$proto" ) >/dev/null 2>/dev/null && eval "stop_interface_$proto '$cfg'"

# make sure all locks are removed
for lock in "/var/lock/dhcp-$iface" "/var/lock/ppp-$iface"; do
	[ -f "$lock" ] && {
		lock -u "$lock"
		sleep 1
	}
done

# kill active ppp daemon and other processes
config_get ifname "$cfg" ifname
pids="$(head -n1 -q /var/run/${ifname}.pid /var/run/ppp-${cfg}.pid 2>/dev/null)"
for pid in $pids; do 
	[ -d "/proc/$pid" ] && {
		kill $pid
		[ -d "/proc/$pid" ] && {
			sleep 1
			kill -9 $pid 2>/dev/null >/dev/null
		}
	}
done
rm -f /var/run/${ifname}.pid /var/run/ppp-${cfg}.pid

config_get ifname "$cfg" ifname
config_get device "$cfg" device

[ ."$device" != ."$ifname" ] || device=
for dev in $ifname $device; do
	ifconfig "$dev" 0.0.0.0 down >/dev/null 2>/dev/null
done

config_get iftype "$cfg" type
[ "$iftype" = "bridge" ] && brctl delbr "$ifname" >/dev/null 2>/dev/null

