#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

# Initialize hook variables et by pulling in from preinit

preinit_essential_hook=
preinit_main_hook=
failsafe_hook=
initramfs_hook=
preinit_mount_root=

. /lib/functions/boot.sh

for pi_source_file in /lib/preinit/*; do
    . $pi_source_file
done

# Override function that doesn't apply to use of mount_root as a command rather
# than as part of preinit

preinit_echo() {
    echo "$@"
}

boot_run_hook mount_root
