#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Argon >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Argon=/luci-static/argon
		set luci.main.mediaurlbase=/luci-static/argon
		commit luci
	EOF
fi

exit 0
