#!/bin/sh /etc/rc.common
#
# Activate Voice CPE TAPI subsystem LL driver for VMMC

START=31

start() {
	config_load vmmc
	config_get GROUP nodes group ""

	if [ -n "$GROUP" ]; then
		group_exists "$GROUP" || GROUP=
	fi

	for i in 10 11 12 13 14 15 16 17 18; do
		if ! [ -e /dev/vmmc$i ]; then
			mknod -m 664 /dev/vmmc$i c 122 $i
			[ -n "$GROUP" ] && [ -c /dev/vmmc$i ] && \
				chown :"$GROUP" /dev/vmmc$i
		fi
	done
}
