#!/bin/sh

LOG_D=/var/log
RUN_D=/var/run
PID_F=$RUN_D/dhcpd-fwd.pid

case $1 in
 start)
  [ -d $LOG_D ] || mkdir -p $LOG_D
  [ -d $RUN_D ] || mkdir -p $RUN_D
  dhcp-fwd >/dev/null 2>&1
  ;;
 stop)
  [ -f $PID_F ] && kill $(cat $PID_F) >/dev/null 2>&1
  ;;
 *)
  echo "usage: $0 (start|stop)"
  exit 1
esac

exit $?
