#!/bin/sh

# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

mount_no_mtd() {
    mtd unlock rootfs
    mount -o noatime,remount,rw /dev/root /
}

check_for_mtd() {
    check_skip || {
	grep -qs rootfs_data /proc/mtd || {
	    mount_no_mtd && pi_mount_skip_next=true
	}
    }
}

boot_hook_add preinit_mount_root check_for_mtd

