#
# Automatically generated by make menuconfig: don't edit
#

#
# General Setup
#
CONFIG_TC_3_3_6=y
TOOLCHAIN_DIR="/opt/uclibc-toolchain/ifx-lxdb-1-2"
BUILD_DIR="/mnt/the-noob/build"
BUILD_VOB="n"
# COPY_TFTP is not set
TOPDIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0/"
KERNEL_SOURCE_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/kernel/opensource/linux-2.4.31/"
BUILD_ROOTFS_DIR="/mnt/the-noob/build/root_filesystem/"
UBOOT_SOURCE_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/u-boot/"
USER_SOURCE_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/"
USER_IFXSOURCE_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx/"
USER_OPENSOURCE_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/opensource/"
IFX_APIS_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx/IFXAPIs/"
KERNEL_IFX_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/kernel/ifx/"
BUILD_TOOLS_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//tools/build_tools/"
KERNEL_CONFIG="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/kernel/opensource/linux-2.4.31//.config"
TOOLS_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0/tools/build_tools"
VER_FILE="/mnt/CD1_BSP/software/ReleasePackage/3.3.0/tools/build_tools/versions"
IFX_HOSTCC="gcc"
BUILD="i686-pc-linux-gnu"
HOSTUTILS_PATH="/opt/uclibc-toolchain/ifx-lxdb-1-2/hostutils/bin"
FAKE_ENV="/mnt/the-noob/build/fakeroot.env"
DEV_FILE="/mnt/CD1_BSP/software/ReleasePackage/3.3.0/tools/build_tools/device_table.txt"

#
# Platform Configuration
#
# CONFIG_AMZ is not set
# CONFIG_AMZ_SE is not set
CONFIG_DNB=y
CONFIG_G0432V33_BSP=y
PLATFORM_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0/platforms/Danube"
MODEL="G0432V33_BSP"
CONFIG_MIPS=y
CONFIG_UIMAGE_LZMA=y
CONFIG_FS_OTHER=y
PLATFORM_NAME="Danube"
BSP_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0/platforms/Danube/source/kernel/ifx"
CONFIG_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//config"
IFXAPI_SRC_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx/IFXAPIs//src"
IFXAPI_INC_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx/IFXAPIs//include"
CONFIG_MGMT_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx//ConfigManagementProcess"
IFX_HTTPD_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx//ifx_httpd"
IFX_UTIL_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx//utilities"
IFX_NFEXT_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx//nfext"
IFX_ROOTFS_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/rootfs.bsp/"
ROOTFS_SOURCE_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/rootfs.bsp/flashdisk"
IFX_CFLAGS="-Os -mips32 -mtune=4kc -I/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx//IFXAPIs/include"
IFX_LDFLAGS="-L/mnt/the-noob/build/root_filesystem//lib -Wl,-rpath-link,/mnt/the-noob/build/root_filesystem//lib"
VOIP_SRC_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx/gateway-sip"
TR69_SRC_DIR="/mnt/CD1_BSP/software/ReleasePackage/3.3.0//source/user/ifx/tr69"
CONFIG_ENDIAN="mips"
COMPILER_PREFIX="mips-linux-"
TOOLCHAIN_PATH="/opt/uclibc-toolchain/ifx-lxdb-1-2/gcc-3.3.6/toolchain-mips/bin"
COMPILER_PREFIX="mips-linux-"
LIBPATH="/opt/uclibc-toolchain/ifx-lxdb-1-2/gcc-3.3.6/toolchain-mips/lib"
CCACHE_PATH="/opt/uclibc-toolchain/ifx-lxdb-1-2/gcc-3.3.6/toolchain-mips/bin-ccache"
IFX_CC="mips-linux-gcc"
IFX_AR="mips-linux-ar"
IFX_AS="mips-linux-as"
IFX_LD="mips-linux-ld"
IFX_NM="mips-linux-nm"
IFX_STRIP="mips-linux-strip"
IFX_RANLIB="mips-linux-ranlib"
IFX_CXX="mips-linux-g++"
IFX_CPP="mips-linux-cpp"
IFX_OBJCOPY="mips-linux-objcopy"
IFX_OBJDUMP="mips-linux-objdump"
TARGET="mips-linux"
HOST="mips-linux"

#
# Library Configuration
#
# CONFIG_LIB_FEATURE is not set
RECONFIG=y
# NEW_DEFAULTS is not set
# NEW_MODEL is not set

####    End of Configuration   ####

. /mnt/CD1_BSP/software/ReleasePackage/3.3.0/tools/build_tools/.gen_funcs
. /mnt/CD1_BSP/software/ReleasePackage/3.3.0/tools/build_tools/.board_funcs
