LOC_DIR=/src/adpt
LIB=ADPT

include $(PRJ_PATH)/make/config.mk

SRC_LIST=adpt.c

include $(PRJ_PATH)/make/components.mk
include $(PRJ_PATH)/make/defs.mk
include $(PRJ_PATH)/make/target.mk

all: dep obj
