set showcmd            " Show (partial) command in status line.
set showmatch          " Show matching brackets.
set ignorecase         " Do case insensitive matching
set incsearch          " Incremental search
set autowrite          " Automatically save before commands like :next and :make
set nocompatible        " Use Vim defaults instead of 100% vi compatibility
set backspace=indent,eol,start  " more powerful backspacing
set autoindent          " always set autoindenting on
set linebreak         " Don't wrap words by default
set textwidth=0         " Don't wrap lines by default
set ruler               " show the cursor position all the time


