#!/bin/sh /etc/rc.common
# (C) 2020 Developer X <dev@x-wrt.com>

START=19
STOP=90

boot() {
	#power on ec20_1
	echo "1" >/sys/class/gpio/ec20_1_4v_en/value

	#reset ec20_1
	echo "0" >/sys/class/gpio/ec20_1_reset/value
	sleep 1
	echo "1" >/sys/class/gpio/ec20_1_reset/value


	#power on ec20_2
	echo "1" >/sys/class/gpio/ec20_2_4v_en/value

	#reset ec20_2
	echo "0" >/sys/class/gpio/ec20_2_reset/value
	sleep 1
	echo "1" >/sys/class/gpio/ec20_2_reset/value
}
