#!/bin/sh
mount none /proc -t proc
mtd unlock mtd4
sleep 1
if /sbin/resetmon ; then
  mount -t jffs2 /dev/mtdblock/4 /jffs
  pivot_root /jffs /jffs/rom
  mount none /dev -t devfs
  mount none /proc -t proc
  umount rom/proc
  umount rom/dev
else
  FAILSAFE=true
  export FAILSAFE
fi
mount none /tmp -t ramfs
exec /sbin/init
