obj-m += 80211.o rc80211_simple.o

80211-objs := \
	ieee80211.o \
	ieee80211_ioctl.o \
	sta_info.o \
	wep.o \
	wpa.o \
	ieee80211_scan.o \
	ieee80211_sta.o \
	ieee80211_dev.o \
	ieee80211_iface.o \
	ieee80211_rate.o \
	ieee80211_sysfs.o \
	ieee80211_sysfs_sta.o \
	michael.o \
	tkip.o \
	aes_ccm.o \
	wme.o \
	fifo_qdisc.o
