#!/bin/sh
[ "$1" = "firmware" -a "$ACTION" = "add" ] && {
	[ -f "/lib/firmware/$FIRMWARE" ] && {
		echo 1 > "/sys$DEVPATH/loading"
		cp "/lib/firmware/$FIRMWARE" "/sys$DEVPATH/data"
		echo 0 > "/sys$DEVPATH/loading"
	}
	exit 0
}

[ -e /tmp/.failsafe ] && {
	export FAILSAFE=true
} || {
	[ -e /etc/config/network ] && . /etc/config/network
}
. /etc/functions.sh
. /etc/network.overrides

PATH=/bin:/sbin:/usr/bin:/usr/sbin
LOGNAME=root
USER=root
export PATH LOGNAME USER

[ \! -z "$1" -a -d /etc/hotplug.d/$1 ] && {
	for script in $(ls /etc/hotplug.d/$1/* 2>&-); do (
		[ -f $script ] && . $script
	); done
}
