#!/bin/sh
[ -e /tmp/.failsafe ] && {
	export FAILSAFE=true
} || {
	[ -e /etc/config/network ] && . /etc/config/network
}
. /etc/functions.sh
. /etc/network.overrides

PATH=/bin:/sbin:/usr/bin:/usr/sbin
LOGNAME=root
USER=root
export PATH LOGNAME USER

[ \! -z "$1" -a -d /etc/hotplug.d/$1 ] && {
	for script in $(ls /etc/hotplug.d/$1/* 2>&-); do (
		[ -f $script ] && . $script
	); done
}
