#!/bin/ash
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
. /etc/functions.sh
. /etc/network.overrides
[ -e /etc/config/network ] && . /etc/config/network
type=$1
debug "### ifdown $type ###"
if=$(nvram get ${type}_ifname)
if_valid $if || exit 
$DEBUG ifconfig $if down
kill $(cat /var/run/${if}.pid 2>&-) 2>&-
