#!/bin/sh
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
. /etc/functions.sh
. /etc/network.overrides
[ "$FAILSAFE" != "true" -a -e /etc/config/network ] && . /etc/config/network

ifdown $1

debug "### ifup $type ###"
type=$1

if_proto=$(nvram get ${type}_proto)
if=$(nvram get ${type}_ifname)

case "$if_proto" in
	pppoa) hotplug_dev register atm0; exit 0 ;;
	pppoe)
		ifconfig nas0 2>&- >&- || {
			hotplug_dev register atm0
			exit 0
		}
	;;
	none|"") exit 0;;
esac

if [ "${if%%[0-9]}" = "br" ]; then
	for sif in $(nvram get ${type}_ifnames); do
		hotplug_dev register "$sif"
	done
else
	hotplug_dev register "$if"
fi
