#!/bin/sh
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
. /etc/functions.sh
. /etc/config/network

ifdown $1

debug "### ifup $type ###"
type=$1

eval "if_proto=\"\${${type}_proto}\""
eval "if=\"\${${type}_ifname}\""
[ "${if%%[0-9]}" = "ppp" ] && eval "if=\"\${${type}_device}\""

case "$if_proto" in
	pppoa) hotplug_dev register atm0; exit 0 ;;
	pppoe)
		# PPPoE over ATM
		[ "$if" = "nas0" ] && {
			ifconfig nas0 2>&- >&- || {
				hotplug_dev register atm0
				exit 0
			}
		}
	;;
	none|"") exit 0;;
esac

if [ "${if%%[0-9]}" = "br" ]; then
	eval "ifnames=\"\${${type}_ifnames}\""
	for sif in $ifnames; do
		hotplug_dev register "$sif"
	done
else
	hotplug_dev register "$if"
fi
