
#define	DNSMASQ_SUPPORT	1
#define	CONFIG_DNSMASQ	y
#define	UDHCPD_SUPPORT	1
#define	CONFIG_UDHCPD	y
#define	UDHCPC_SUPPORT	1
#define	CONFIG_UDHCPC	y
#define	PPPOE_SUPPORT	1
#define	CONFIG_PPPOE	y
#define	PPTP_SUPPORT	1
#define	CONFIG_PPTP	y
#define	L2TP_SUPPORT	1
#define	CONFIG_L2TP	y
#define	PPPD_SUPPORT	1
#define	CONFIG_PPPD	y
#define	ZEBRA_SUPPORT	1
#define	CONFIG_ZEBRA	y
#define	TFTPD_SUPPORT	1
#define	CONFIG_TFTPD	y
#define	DDNS_SUPPORT	1
#define	CONFIG_DDNS	y
#define	CRON_SUPPORT	1
#define	CONFIG_CRON	y
#define	HTTPD_SUPPORT	1
#define	CONFIG_HTTPD	y
#define	GET_POST_SUPPORT	1
#define	CONFIG_GET_POST	y

#if 1
#define	HEARTBEAT_SUPPORT	1
#define	CONFIG_HEARTBEAT	y
#define	MULTICAST_SUPPORT	1
#define	CONFIG_MULTICAST	y
#define	SETUP_WIZARD_SUPPORT	1
#define	CONFIG_SETUP_WIZARD	y
#define	PARENTAL_CONTROL_SUPPORT	1
#define	CONFIG_PARENTAL_CONTROL	y
#define	HTTPS_SUPPORT	1
#define	CONFIG_HTTPS	y
#define	EOU_SUPPORT	1
#define	CONFIG_EOU	y
#define	EZC_SUPPORT	1
#define	CONFIG_EZC	y
#define	WRITE_MAC_SUPPORT	1
#define	CONFIG_WRITE_MAC	y
#define	DIAG_SUPPORT	1
#define	CONFIG_DIAG	y
#endif

#define	SPEED_BOOSTER_SUPPORT	1
#define	CONFIG_SPEED_BOOSTER	y
#define	XBOX_SUPPORT	1
#define	CONFIG_XBOX	y

#if 0
#define	MPPPOE_SUPPORT	1
#define	CONFIG_MPPPOE	y
#define	UNNUMBERIP_SUPPORT	1
#define	CONFIG_UNNUMBERIP	y
#endif

#define	WL_STA_SUPPORT	1
#define	CONFIG_WL_STA	y
#define	BACKUP_RESTORE_SUPPORT	1
#define	CONFIG_BACKUP_RESTORE	y
#define	PORT_TRIGGER_SUPPORT	1
#define	CONFIG_PORT_TRIGGER	y
#define	HW_QOS_SUPPORT	1
#define	CONFIG_HW_QOS	y
