#!/bin/sh
uci add rtty rtty
uci set rtty.@rtty[-1].id=$(cat /sys/class/net/eth0/address | tr -d :)
uci set rtty.@rtty[-1].description="$(cat /tmp/sysinfo/model)"
uci set rtty.@rtty[-1].ssl=1
uci set rtty.@rtty[-1].port='5912'
