#!/bin/sh
# Copyright (C) 2010 Vertical Communications

# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.

# Determine if we are requested to mount external root

external_root_pivot() {
	check_skip || [ "$pi_extroot_mount_success" != "true" ] || {
		echo "switching to external rootfs"
		if [ "$ER_IS_SQUASHFS" = "true" ]; then
			umount /tmp/overlay
		fi
		mount -o remount,ro / && fopivot /overlay /rom && pi_mount_skip_next=true
	}
}

boot_hook_add preinit_mount_root external_root_pivot

