FROM registry.gitlab.com/openwrt/buildbot/buildworker-3.4.1

COPY --chown=buildbot staging_dir/host /prebuilt_tools/staging_dir/host
COPY --chown=buildbot build_dir/host /prebuilt_tools/build_dir/host
