name: Merge Main to My-OpenWrt #合并OpenWrt_main到My-OpenWrt分支

on:
  schedule:
    - cron: '30 2 * * *'  # 每天UTC时间2:30自动合并
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My-OpenWrt branch
        uses: actions/checkout@v4
        with:
          ref: My-OpenWrt
          persist-credentials: false

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch main from origin
        run: |
          git fetch origin main

      - name: Merge main into My-OpenWrt
        run: |
          git merge origin/main --no-edit || true

      - name: Push updates to My-OpenWrt branch
        run: |
          git push origin My-OpenWrt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
